"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Loader2, RefreshCw, Sparkles } from "lucide-react";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { Button } from "@/components/ui/button";

interface Idea {
  title: string;
  description: string;
  techStack: string[];
  difficulty: "Easy" | "Medium" | "Hard";
  impact: string;
  estimatedTime: string;
}

const difficultyClass: Record<Idea["difficulty"], string> = {
  Easy: "border-emerald-400/30 text-emerald-300",
  Medium: "border-amber-400/30 text-amber-300",
  Hard: "border-accent/40 text-accent-light",
};

export default function IdeasPage() {
  const [ideas, setIdeas] = useState<Idea[]>([]);
  const [loading, setLoading] = useState(true);

  async function load(fresh = false) {
    setLoading(true);
    try {
      const response = await fetch(fresh ? "/api/ideas?fresh=1" : "/api/ideas", {
        cache: fresh ? "no-store" : "default",
      });
      const payload = (await response.json()) as { ideas?: Idea[] };
      setIdeas(payload.ideas ?? []);
    } catch {
      setIdeas([]);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void load(false);
  }, []);

  return (
    <>
      <Navbar />
      <main className="section-wrap section-shell pt-28">
        <div className="flex flex-wrap items-end justify-between gap-4">
          <div>
            <p className="inline-flex items-center gap-2 font-mono text-xs tracking-[0.2em] text-accent uppercase">
              <Sparkles className="size-3.5" />
              Ideas
            </p>
            <h1 className="mt-3 font-heading text-3xl font-semibold tracking-tight sm:text-4xl">
              AI-Suggested Projects
            </h1>
            <p className="mt-3 max-w-xl text-sm text-text-muted">
              Fresh ideas generated by AI, updated daily
            </p>
          </div>
          <Button
            type="button"
            variant="outline"
            onClick={() => void load(true)}
            disabled={loading}
            className="rounded-full"
          >
            {loading ? (
              <Loader2 className="size-4 animate-spin" />
            ) : (
              <RefreshCw className="size-4" />
            )}
            Refresh
          </Button>
        </div>

        <motion.ul
          initial="hidden"
          animate="show"
          variants={{
            hidden: {},
            show: { transition: { staggerChildren: 0.08 } },
          }}
          className="mt-12 grid gap-5 md:grid-cols-2"
        >
          {ideas.map((idea) => (
            <motion.li
              key={idea.title}
              variants={{
                hidden: { opacity: 0, y: 16 },
                show: { opacity: 1, y: 0 },
              }}
              className="rounded-2xl border border-white/8 bg-surface p-6"
            >
              <div className="flex items-start justify-between gap-3">
                <h2 className="font-heading text-xl font-semibold">{idea.title}</h2>
                <span
                  className={`rounded-full border px-2.5 py-1 text-[11px] ${difficultyClass[idea.difficulty]}`}
                >
                  {idea.difficulty}
                </span>
              </div>
              <p className="mt-3 text-sm leading-6 text-text-primary/80">
                {idea.description}
              </p>
              <div className="mt-4 flex flex-wrap gap-2">
                {idea.techStack.map((tech) => (
                  <span
                    key={tech}
                    className="rounded-full border border-white/8 px-2.5 py-1 text-[11px] text-text-muted"
                  >
                    {tech}
                  </span>
                ))}
              </div>
              <p className="mt-4 text-sm text-text-muted">{idea.impact}</p>
              <p className="mt-1 text-xs text-accent-light">{idea.estimatedTime}</p>
              <a
                href="https://github.com/new"
                target="_blank"
                rel="noopener noreferrer"
                className="mt-5 inline-flex rounded-full bg-gradient-to-r from-accent to-accent-light px-4 py-2 text-sm text-white"
              >
                Start Building
              </a>
            </motion.li>
          ))}
        </motion.ul>
      </main>
      <Footer />
    </>
  );
}
